drivers: slimbus: remove unused variable "dev"
../drivers/slimbus/slim-msm-ngd.c:1030:31: error: unused variable 'dev' [-Werror=unused-variable]
 1030 |         struct msm_slim_ctrl *dev = slim_get_ctrldata(ctrl);
      |                               ^~~

Signed-off-by: CloudedQuartz <ravenklawasd@gmail.com>