drivers: pci: remove an unused variable "pcie_dev"
../drivers/pci/host/pci-msm.c:6268:32: error: unused variable 'pcie_dev' [-Werror=unused-variable]
 6268 |         struct msm_pcie_dev_t *pcie_dev = PCIE_BUS_PRIV_DATA(dev->bus);
      |                                ^~~~~~~~

Signed-off-by: CloudedQuartz <ravenklawasd@gmail.com>